### PR TITLE
Delete ocamllint

### PR DESCRIPTION
**Pull request by andschwa**
The author has archived the repository as the project is no longer developed or supported.

### CODE REVIEW

**Comment by gasche** [comment]
Thanks! Out of curiosity, the deprecation message mentions "there are better and more flexible lint tools than a standalone library", do you know which tools they are thinking of? (What's the state of the art for linting of OCaml programs?) Are they mentioned in awesome-ocaml? (cc @NathanReb)

**Comment by NathanReb** [comment]
The idea was to extract a library that exposes a few rules roughly as `ast -> ast` functions that raise compiler warnings so that one can build its own set of rules to apply with the `dune` lint tool. This was used at Cryptosense for instance where we had our own lint library to define our rules and I believe this is still the case as of today, @leamingrad can probably confirm.

Last time I checked this `dune` feature wasn't documented yet but I'm happy to push this forward if there are people interested!

**Comment by NathanReb** [comment]
cc @emillon who initially set up the dune lint thing there btw!

**Comment by emillon** [comment]
Yes I think it can safely be removed. Thanks!

**Comment by gasche** [comment]
> Last time I checked this dune feature wasn't documented yet but I'm happy to push this forward if there are people interested!

Well yes? I would be interested in a documentation of linting in the Dune documentation, and in a blog post advertising the feature. (Maybe writing the blog post first is a good way to figure what to have in the documentation.)

**Comment by leamingrad** [comment]
I can confirm that we still use the rules we have defined at cryptosense with the `dune` lint tool as @NathanReb mentions above.

I think most of the stuff in there is generally applicable (although @emillon knows more about this), so we would be open to pushing that out as a library (maybe alongside some new `dune` documentation and a blog post so it can be used as a concrete example by others), but that is probably a discussion for another thread.

**Comment by emillon** [comment]
OK, I've been meaning to write something about this for a long time so I'll take a shot of this over the next couple weeks.

**Pull request merged**
