### PR TITLE
added ocaml-sklearn in ML section

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by XVilka** [comment]
Please start the commit from the capital letter and remove the unnecessary newline.

**Comment by UnixJunkie** [comment]
Done. Not that for such cosmetic changes, usually maintainers just amend the PR.

**Comment by XVilka** [comment]
I am not a maintainer though.

**Comment by kanishka-work** [comment]
Link works, the unrelated failures in CI have since been fixed

**Pull request merged**
