### PR TITLE
Mention the learn-ocaml project

### PR DESCRIPTION
**Pull request by erikmd**
Just FYI @yurug @AltGr @gasche @brabalan

### CODE REVIEW

**Comment by rizo** [comment]
Hi @erikmd! Thanks for adding this.

My preference would be to only include the first link in the "Exercises and Short Examples" section. It's the only one that fits perfectly.

As for other, feel free to suggest a different placing in the document.

**Comment by erikmd** [comment]
Thanks @rizo !

Indeed, the last 2 links were not at the optimal place.

I believe a good place would be `Developer Tools`, which already lists these 5 links that are related:

[Try OCaml](https://try.ocamlpro.com/) – Try OCaml in your web browser.

[BetterOCaml](https://betterocaml.ml/) – An efficient, intuitive, and cross-platform web IDE with your OCaml code interpreted and running in your browser!

[codingground](https://www.tutorialspoint.com/compile_ocaml_online.php) – Compile and execute OCaml code online.

[OCaml: Learn & Code iOS app](https://apps.apple.com/app/ocaml-learn-code/id1547506826) - Learn and execute OCaml code from your iPhone/iPad/Mac.

[Jupyter](https://github.com/akabe/ocaml-jupyter) – An OCaml kernel for the Jupyter notebook

Will force-push my commit

**Comment by rizo** [comment]
Thank you!

**Comment by erikmd** [comment]
Hi again, so I proposed to add them just after Try OCaml, because it happens learn-ocaml and Try-OCaml do share code! (indeed like Try-OCaml, learn-ocaml was an ocamlpro software at first :)

**Pull request merged**
